services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      # улучшает работу HMR в Docker-Desktop под Windows / macOS
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./frontend:/app:cached         
      - frontend_node_modules:/app/node_modules
    depends_on:
      - backend
    stdin_open: true
    tty: true

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    env_file: ./backend/.env           
    volumes:
      - ./backend:/app:cached
      - backend_node_modules:/app/node_modules
    depends_on:
      - db
    stdin_open: true
    tty: true

  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER:     postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB:       postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  frontend_node_modules:
  backend_node_modules:
  postgres_data:
